language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

script:
  - cargo build
  - cargo test
