[package]
name = "hyper-alpn"
version = "0.2.0-alpha.6"
authors = ["Julius de Bruijn <julius@nauk.io>"]
license = "MIT"
readme  = "README.md"
description = "An ALPN implementation to be used with Hyper 0.12"
keywords = ["hyper", "alpn", "http2", "h2"]
repository = "https://github.com/pimeys/hyper-alpn.git"
homepage = "https://github.com/pimeys/hyper-alpn"
documentation = "https://docs.rs/hyper-alpn/"
edition = "2018"

[dependencies]
rustls = "0.16"
webpki = "0.21"
webpki-roots = "0.17"
log = "0.4"

futures = "0.3"
tokio-rustls = "0.12"
tokio = { version = "0.2", features = ["net"] }
hyper = { git = "https://github.com/hyperium/hyper" }
async-std = "1"

[dev-dependencies]
openssl = "0.10"
tokio = { version = "0.2", features = ["macros", "rt-threaded", "net"] }
